/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AlbumId = IDL.Text;
export const CharmType = IDL.Variant({
  'custom' : IDL.Null,
  'preset' : IDL.Null,
});
export const Charm = IDL.Record({
  'id' : IDL.Text,
  'charmType' : CharmType,
  'labelText' : IDL.Text,
  'presetId' : IDL.Text,
  'position' : IDL.Nat,
  'customKey' : IDL.Opt(IDL.Text),
});
export const ScrapbookId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EnvelopeTexture = IDL.Variant({
  'gingham' : IDL.Null,
  'frosted' : IDL.Null,
  'holographic' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const MusicLoop = IDL.Variant({
  'lofi' : IDL.Null,
  'kawaiiPop' : IDL.Null,
});
export const UnboxingType = IDL.Variant({
  'musicBox' : IDL.Null,
  'polaroidStack' : IDL.Null,
  'strawberryJar' : IDL.Null,
  'cloverField' : IDL.Null,
  'fruitSoda' : IDL.Null,
  'secretLocket' : IDL.Null,
  'openWhen' : IDL.Null,
  'cdStickerPeeler' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Photo = IDL.Record({ 'blob' : ExternalBlob });
export const CreateLetterInput = IDL.Record({
  'patternKey' : IDL.Opt(IDL.Text),
  'note' : IDL.Text,
  'envelopeTexture' : EnvelopeTexture,
  'receiverLink' : IDL.Text,
  'secretNote' : IDL.Opt(IDL.Text),
  'openWhenTime' : IDL.Opt(Timestamp),
  'musicLoop' : IDL.Opt(MusicLoop),
  'unboxingType' : UnboxingType,
  'photos' : IDL.Vec(Photo),
});
export const LetterId = IDL.Text;
export const AlbumEntry = IDL.Record({
  'photoKeys' : IDL.Vec(IDL.Text),
  'note' : IDL.Text,
  'addedAt' : IDL.Int,
  'contributor' : IDL.Principal,
});
export const Album = IDL.Record({
  'id' : AlbumId,
  'theme' : IDL.Text,
  'creator' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'completed' : IDL.Bool,
  'memberQueue' : IDL.Vec(IDL.Principal),
  'currentHolderIdx' : IDL.Nat,
  'entries' : IDL.Vec(AlbumEntry),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'besties' : IDL.Vec(IDL.Principal),
  'avatar' : IDL.Opt(ExternalBlob),
});
export const Letter = IDL.Record({
  'id' : LetterId,
  'patternKey' : IDL.Opt(IDL.Text),
  'note' : IDL.Text,
  'createdAt' : Timestamp,
  'isRead' : IDL.Bool,
  'sender' : IDL.Principal,
  'envelopeTexture' : EnvelopeTexture,
  'receiverLink' : IDL.Text,
  'secretNote' : IDL.Opt(IDL.Text),
  'openWhenTime' : IDL.Opt(Timestamp),
  'musicLoop' : IDL.Opt(MusicLoop),
  'unboxingType' : UnboxingType,
  'photos' : IDL.Vec(Photo),
});
export const ScrapbookPost = IDL.Record({
  'id' : IDL.Text,
  'note' : IDL.Text,
  'createdAt' : IDL.Int,
  'photoKey' : IDL.Text,
  'author' : IDL.Principal,
});
export const Scrapbook = IDL.Record({
  'id' : ScrapbookId,
  'creator' : IDL.Principal,
  'members' : IDL.Vec(IDL.Principal),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'posts' : IDL.Vec(ScrapbookPost),
});
export const PhoneStrap = IDL.Record({
  'owner' : IDL.Principal,
  'charms' : IDL.Vec(Charm),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addAlbumContent' : IDL.Func(
      [AlbumId, IDL.Vec(IDL.Text), IDL.Text],
      [IDL.Bool],
      [],
    ),
  'addBestie' : IDL.Func([IDL.Principal], [], []),
  'addCharm' : IDL.Func([Charm], [], []),
  'addScrapbookPost' : IDL.Func(
      [ScrapbookId, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAlbum' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Principal)],
      [AlbumId],
      [],
    ),
  'createLetter' : IDL.Func([CreateLetterInput], [LetterId], []),
  'createScrapbook' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Principal)],
      [ScrapbookId],
      [],
    ),
  'getAlbum' : IDL.Func([AlbumId], [IDL.Opt(Album)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInbox' : IDL.Func([IDL.Text], [IDL.Vec(Letter)], ['query']),
  'getLetter' : IDL.Func([LetterId], [IDL.Opt(Letter)], ['query']),
  'getMyAlbums' : IDL.Func([], [IDL.Vec(Album)], ['query']),
  'getMyScrapbooks' : IDL.Func([], [IDL.Vec(Scrapbook)], ['query']),
  'getMyStrap' : IDL.Func([], [PhoneStrap], ['query']),
  'getScrapbook' : IDL.Func([ScrapbookId], [IDL.Opt(Scrapbook)], ['query']),
  'getScrapbookPosts' : IDL.Func(
      [ScrapbookId],
      [IDL.Opt(IDL.Vec(ScrapbookPost))],
      ['query'],
    ),
  'getSent' : IDL.Func([], [IDL.Vec(Letter)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markRead' : IDL.Func([LetterId], [], []),
  'passAlbum' : IDL.Func([AlbumId], [IDL.Bool], []),
  'removeBestie' : IDL.Func([IDL.Principal], [], []),
  'removeCharm' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'reorderCharms' : IDL.Func([IDL.Vec(IDL.Text)], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveMyStrap' : IDL.Func([IDL.Vec(Charm)], [], []),
  'setProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AlbumId = IDL.Text;
  const CharmType = IDL.Variant({ 'custom' : IDL.Null, 'preset' : IDL.Null });
  const Charm = IDL.Record({
    'id' : IDL.Text,
    'charmType' : CharmType,
    'labelText' : IDL.Text,
    'presetId' : IDL.Text,
    'position' : IDL.Nat,
    'customKey' : IDL.Opt(IDL.Text),
  });
  const ScrapbookId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EnvelopeTexture = IDL.Variant({
    'gingham' : IDL.Null,
    'frosted' : IDL.Null,
    'holographic' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const MusicLoop = IDL.Variant({ 'lofi' : IDL.Null, 'kawaiiPop' : IDL.Null });
  const UnboxingType = IDL.Variant({
    'musicBox' : IDL.Null,
    'polaroidStack' : IDL.Null,
    'strawberryJar' : IDL.Null,
    'cloverField' : IDL.Null,
    'fruitSoda' : IDL.Null,
    'secretLocket' : IDL.Null,
    'openWhen' : IDL.Null,
    'cdStickerPeeler' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Photo = IDL.Record({ 'blob' : ExternalBlob });
  const CreateLetterInput = IDL.Record({
    'patternKey' : IDL.Opt(IDL.Text),
    'note' : IDL.Text,
    'envelopeTexture' : EnvelopeTexture,
    'receiverLink' : IDL.Text,
    'secretNote' : IDL.Opt(IDL.Text),
    'openWhenTime' : IDL.Opt(Timestamp),
    'musicLoop' : IDL.Opt(MusicLoop),
    'unboxingType' : UnboxingType,
    'photos' : IDL.Vec(Photo),
  });
  const LetterId = IDL.Text;
  const AlbumEntry = IDL.Record({
    'photoKeys' : IDL.Vec(IDL.Text),
    'note' : IDL.Text,
    'addedAt' : IDL.Int,
    'contributor' : IDL.Principal,
  });
  const Album = IDL.Record({
    'id' : AlbumId,
    'theme' : IDL.Text,
    'creator' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'completed' : IDL.Bool,
    'memberQueue' : IDL.Vec(IDL.Principal),
    'currentHolderIdx' : IDL.Nat,
    'entries' : IDL.Vec(AlbumEntry),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'besties' : IDL.Vec(IDL.Principal),
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const Letter = IDL.Record({
    'id' : LetterId,
    'patternKey' : IDL.Opt(IDL.Text),
    'note' : IDL.Text,
    'createdAt' : Timestamp,
    'isRead' : IDL.Bool,
    'sender' : IDL.Principal,
    'envelopeTexture' : EnvelopeTexture,
    'receiverLink' : IDL.Text,
    'secretNote' : IDL.Opt(IDL.Text),
    'openWhenTime' : IDL.Opt(Timestamp),
    'musicLoop' : IDL.Opt(MusicLoop),
    'unboxingType' : UnboxingType,
    'photos' : IDL.Vec(Photo),
  });
  const ScrapbookPost = IDL.Record({
    'id' : IDL.Text,
    'note' : IDL.Text,
    'createdAt' : IDL.Int,
    'photoKey' : IDL.Text,
    'author' : IDL.Principal,
  });
  const Scrapbook = IDL.Record({
    'id' : ScrapbookId,
    'creator' : IDL.Principal,
    'members' : IDL.Vec(IDL.Principal),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'posts' : IDL.Vec(ScrapbookPost),
  });
  const PhoneStrap = IDL.Record({
    'owner' : IDL.Principal,
    'charms' : IDL.Vec(Charm),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addAlbumContent' : IDL.Func(
        [AlbumId, IDL.Vec(IDL.Text), IDL.Text],
        [IDL.Bool],
        [],
      ),
    'addBestie' : IDL.Func([IDL.Principal], [], []),
    'addCharm' : IDL.Func([Charm], [], []),
    'addScrapbookPost' : IDL.Func(
        [ScrapbookId, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAlbum' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Principal)],
        [AlbumId],
        [],
      ),
    'createLetter' : IDL.Func([CreateLetterInput], [LetterId], []),
    'createScrapbook' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Principal)],
        [ScrapbookId],
        [],
      ),
    'getAlbum' : IDL.Func([AlbumId], [IDL.Opt(Album)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInbox' : IDL.Func([IDL.Text], [IDL.Vec(Letter)], ['query']),
    'getLetter' : IDL.Func([LetterId], [IDL.Opt(Letter)], ['query']),
    'getMyAlbums' : IDL.Func([], [IDL.Vec(Album)], ['query']),
    'getMyScrapbooks' : IDL.Func([], [IDL.Vec(Scrapbook)], ['query']),
    'getMyStrap' : IDL.Func([], [PhoneStrap], ['query']),
    'getScrapbook' : IDL.Func([ScrapbookId], [IDL.Opt(Scrapbook)], ['query']),
    'getScrapbookPosts' : IDL.Func(
        [ScrapbookId],
        [IDL.Opt(IDL.Vec(ScrapbookPost))],
        ['query'],
      ),
    'getSent' : IDL.Func([], [IDL.Vec(Letter)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markRead' : IDL.Func([LetterId], [], []),
    'passAlbum' : IDL.Func([AlbumId], [IDL.Bool], []),
    'removeBestie' : IDL.Func([IDL.Principal], [], []),
    'removeCharm' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'reorderCharms' : IDL.Func([IDL.Vec(IDL.Text)], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveMyStrap' : IDL.Func([IDL.Vec(Charm)], [], []),
    'setProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };