/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Album {
  'id' : AlbumId,
  'theme' : string,
  'creator' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'completed' : boolean,
  'memberQueue' : Array<Principal>,
  'currentHolderIdx' : bigint,
  'entries' : Array<AlbumEntry>,
}
export interface AlbumEntry {
  'photoKeys' : Array<string>,
  'note' : string,
  'addedAt' : bigint,
  'contributor' : Principal,
}
export type AlbumId = string;
export interface Charm {
  'id' : string,
  'charmType' : CharmType,
  'labelText' : string,
  'presetId' : string,
  'position' : bigint,
  'customKey' : [] | [string],
}
export type CharmType = { 'custom' : null } |
  { 'preset' : null };
export interface CreateLetterInput {
  'patternKey' : [] | [string],
  'note' : string,
  'envelopeTexture' : EnvelopeTexture,
  'receiverLink' : string,
  'secretNote' : [] | [string],
  'openWhenTime' : [] | [Timestamp],
  'musicLoop' : [] | [MusicLoop],
  'unboxingType' : UnboxingType,
  'photos' : Array<Photo>,
}
export type EnvelopeTexture = { 'gingham' : null } |
  { 'frosted' : null } |
  { 'holographic' : null };
export type ExternalBlob = Uint8Array;
export interface Letter {
  'id' : LetterId,
  'patternKey' : [] | [string],
  'note' : string,
  'createdAt' : Timestamp,
  'isRead' : boolean,
  'sender' : Principal,
  'envelopeTexture' : EnvelopeTexture,
  'receiverLink' : string,
  'secretNote' : [] | [string],
  'openWhenTime' : [] | [Timestamp],
  'musicLoop' : [] | [MusicLoop],
  'unboxingType' : UnboxingType,
  'photos' : Array<Photo>,
}
export type LetterId = string;
export type MusicLoop = { 'lofi' : null } |
  { 'kawaiiPop' : null };
export interface PhoneStrap { 'owner' : Principal, 'charms' : Array<Charm> }
export interface Photo { 'blob' : ExternalBlob }
export interface Scrapbook {
  'id' : ScrapbookId,
  'creator' : Principal,
  'members' : Array<Principal>,
  'name' : string,
  'createdAt' : bigint,
  'posts' : Array<ScrapbookPost>,
}
export type ScrapbookId = string;
export interface ScrapbookPost {
  'id' : string,
  'note' : string,
  'createdAt' : bigint,
  'photoKey' : string,
  'author' : Principal,
}
export type Timestamp = bigint;
export type UnboxingType = { 'musicBox' : null } |
  { 'polaroidStack' : null } |
  { 'strawberryJar' : null } |
  { 'cloverField' : null } |
  { 'fruitSoda' : null } |
  { 'secretLocket' : null } |
  { 'openWhen' : null } |
  { 'cdStickerPeeler' : null };
export interface UserProfile {
  'name' : string,
  'besties' : Array<Principal>,
  'avatar' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addAlbumContent' : ActorMethod<[AlbumId, Array<string>, string], boolean>,
  'addBestie' : ActorMethod<[Principal], undefined>,
  'addCharm' : ActorMethod<[Charm], undefined>,
  'addScrapbookPost' : ActorMethod<[ScrapbookId, string, string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAlbum' : ActorMethod<[string, string, Array<Principal>], AlbumId>,
  'createLetter' : ActorMethod<[CreateLetterInput], LetterId>,
  'createScrapbook' : ActorMethod<[string, Array<Principal>], ScrapbookId>,
  'getAlbum' : ActorMethod<[AlbumId], [] | [Album]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInbox' : ActorMethod<[string], Array<Letter>>,
  'getLetter' : ActorMethod<[LetterId], [] | [Letter]>,
  'getMyAlbums' : ActorMethod<[], Array<Album>>,
  'getMyScrapbooks' : ActorMethod<[], Array<Scrapbook>>,
  'getMyStrap' : ActorMethod<[], PhoneStrap>,
  'getScrapbook' : ActorMethod<[ScrapbookId], [] | [Scrapbook]>,
  'getScrapbookPosts' : ActorMethod<[ScrapbookId], [] | [Array<ScrapbookPost>]>,
  'getSent' : ActorMethod<[], Array<Letter>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markRead' : ActorMethod<[LetterId], undefined>,
  'passAlbum' : ActorMethod<[AlbumId], boolean>,
  'removeBestie' : ActorMethod<[Principal], undefined>,
  'removeCharm' : ActorMethod<[string], boolean>,
  'reorderCharms' : ActorMethod<[Array<string>], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveMyStrap' : ActorMethod<[Array<Charm>], undefined>,
  'setProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];