/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface ScrapbookPost {
    id: string;
    note: string;
    createdAt: bigint;
    photoKey: string;
    author: Principal;
}
export interface Letter {
    id: LetterId;
    patternKey?: string;
    note: string;
    createdAt: Timestamp;
    isRead: boolean;
    sender: Principal;
    envelopeTexture: EnvelopeTexture;
    receiverLink: string;
    secretNote?: string;
    openWhenTime?: Timestamp;
    musicLoop?: MusicLoop;
    unboxingType: UnboxingType;
    photos: Array<Photo>;
}
export interface CreateLetterInput {
    patternKey?: string;
    note: string;
    envelopeTexture: EnvelopeTexture;
    receiverLink: string;
    secretNote?: string;
    openWhenTime?: Timestamp;
    musicLoop?: MusicLoop;
    unboxingType: UnboxingType;
    photos: Array<Photo>;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Scrapbook {
    id: ScrapbookId;
    creator: Principal;
    members: Array<Principal>;
    name: string;
    createdAt: bigint;
    posts: Array<ScrapbookPost>;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface AlbumEntry {
    photoKeys: Array<string>;
    note: string;
    addedAt: bigint;
    contributor: Principal;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Charm {
    id: string;
    charmType: CharmType;
    labelText: string;
    presetId: string;
    position: bigint;
    customKey?: string;
}
export interface Album {
    id: AlbumId;
    theme: string;
    creator: Principal;
    name: string;
    createdAt: bigint;
    completed: boolean;
    memberQueue: Array<Principal>;
    currentHolderIdx: bigint;
    entries: Array<AlbumEntry>;
}
export type ScrapbookId = string;
export interface PhoneStrap {
    owner: Principal;
    charms: Array<Charm>;
}
export type LetterId = string;
export type AlbumId = string;
export interface UserProfile {
    name: string;
    besties: Array<Principal>;
    avatar?: ExternalBlob;
}
export interface Photo {
    blob: ExternalBlob;
}
export enum CharmType {
    custom = "custom",
    preset = "preset"
}
export enum EnvelopeTexture {
    gingham = "gingham",
    frosted = "frosted",
    holographic = "holographic"
}
export enum MusicLoop {
    lofi = "lofi",
    kawaiiPop = "kawaiiPop"
}
export enum UnboxingType {
    musicBox = "musicBox",
    polaroidStack = "polaroidStack",
    strawberryJar = "strawberryJar",
    cloverField = "cloverField",
    fruitSoda = "fruitSoda",
    secretLocket = "secretLocket",
    openWhen = "openWhen",
    cdStickerPeeler = "cdStickerPeeler"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addAlbumContent(albumId: AlbumId, photoKeys: Array<string>, note: string): Promise<boolean>;
    addBestie(bestie: Principal): Promise<void>;
    addCharm(charm: Charm): Promise<void>;
    addScrapbookPost(scrapbookId: ScrapbookId, photoKey: string, note: string): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAlbum(name: string, theme: string, members: Array<Principal>): Promise<AlbumId>;
    createLetter(input: CreateLetterInput): Promise<LetterId>;
    createScrapbook(name: string, members: Array<Principal>): Promise<ScrapbookId>;
    getAlbum(id: AlbumId): Promise<Album | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getInbox(receiverLink: string): Promise<Array<Letter>>;
    getLetter(id: LetterId): Promise<Letter | null>;
    getMyAlbums(): Promise<Array<Album>>;
    getMyScrapbooks(): Promise<Array<Scrapbook>>;
    getMyStrap(): Promise<PhoneStrap>;
    getScrapbook(id: ScrapbookId): Promise<Scrapbook | null>;
    getScrapbookPosts(id: ScrapbookId): Promise<Array<ScrapbookPost> | null>;
    getSent(): Promise<Array<Letter>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markRead(id: LetterId): Promise<void>;
    passAlbum(albumId: AlbumId): Promise<boolean>;
    removeBestie(bestie: Principal): Promise<void>;
    removeCharm(charmId: string): Promise<boolean>;
    reorderCharms(charmIds: Array<string>): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveMyStrap(charms: Array<Charm>): Promise<void>;
    setProfile(profile: UserProfile): Promise<void>;
}
import type { Album as _Album, Charm as _Charm, CharmType as _CharmType, CreateLetterInput as _CreateLetterInput, EnvelopeTexture as _EnvelopeTexture, ExternalBlob as _ExternalBlob, Letter as _Letter, LetterId as _LetterId, MusicLoop as _MusicLoop, PhoneStrap as _PhoneStrap, Photo as _Photo, Scrapbook as _Scrapbook, ScrapbookPost as _ScrapbookPost, Timestamp as _Timestamp, UnboxingType as _UnboxingType, UserProfile as _UserProfile, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addAlbumContent(arg0: AlbumId, arg1: Array<string>, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addAlbumContent(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAlbumContent(arg0, arg1, arg2);
            return result;
        }
    }
    async addBestie(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBestie(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBestie(arg0);
            return result;
        }
    }
    async addCharm(arg0: Charm): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCharm(to_candid_Charm_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCharm(to_candid_Charm_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addScrapbookPost(arg0: ScrapbookId, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addScrapbookPost(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addScrapbookPost(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAlbum(arg0: string, arg1: string, arg2: Array<Principal>): Promise<AlbumId> {
        if (this.processError) {
            try {
                const result = await this.actor.createAlbum(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAlbum(arg0, arg1, arg2);
            return result;
        }
    }
    async createLetter(arg0: CreateLetterInput): Promise<LetterId> {
        if (this.processError) {
            try {
                const result = await this.actor.createLetter(await to_candid_CreateLetterInput_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLetter(await to_candid_CreateLetterInput_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createScrapbook(arg0: string, arg1: Array<Principal>): Promise<ScrapbookId> {
        if (this.processError) {
            try {
                const result = await this.actor.createScrapbook(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createScrapbook(arg0, arg1);
            return result;
        }
    }
    async getAlbum(arg0: AlbumId): Promise<Album | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlbum(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlbum(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInbox(arg0: string): Promise<Array<Letter>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInbox(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInbox(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLetter(arg0: LetterId): Promise<Letter | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLetter(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLetter(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyAlbums(): Promise<Array<Album>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAlbums();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAlbums();
            return result;
        }
    }
    async getMyScrapbooks(): Promise<Array<Scrapbook>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyScrapbooks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyScrapbooks();
            return result;
        }
    }
    async getMyStrap(): Promise<PhoneStrap> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyStrap();
                return from_candid_PhoneStrap_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyStrap();
            return from_candid_PhoneStrap_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScrapbook(arg0: ScrapbookId): Promise<Scrapbook | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getScrapbook(arg0);
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScrapbook(arg0);
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScrapbookPosts(arg0: ScrapbookId): Promise<Array<ScrapbookPost> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getScrapbookPosts(arg0);
                return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScrapbookPosts(arg0);
            return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSent(): Promise<Array<Letter>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSent();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSent();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markRead(arg0: LetterId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markRead(arg0);
            return result;
        }
    }
    async passAlbum(arg0: AlbumId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.passAlbum(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.passAlbum(arg0);
            return result;
        }
    }
    async removeBestie(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeBestie(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeBestie(arg0);
            return result;
        }
    }
    async removeCharm(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeCharm(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeCharm(arg0);
            return result;
        }
    }
    async reorderCharms(arg0: Array<string>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderCharms(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderCharms(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n59(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n59(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveMyStrap(arg0: Array<Charm>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMyStrap(to_candid_vec_n61(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMyStrap(to_candid_vec_n61(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setProfile(await to_candid_UserProfile_n59(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProfile(await to_candid_UserProfile_n59(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_CharmType_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CharmType): CharmType {
    return from_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function from_candid_Charm_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Charm): Charm {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
function from_candid_EnvelopeTexture_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EnvelopeTexture): EnvelopeTexture {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_Letter_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Letter): Promise<Letter> {
    return await from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_MusicLoop_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MusicLoop): MusicLoop {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_PhoneStrap_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PhoneStrap): PhoneStrap {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
async function from_candid_Photo_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Photo): Promise<Photo> {
    return await from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_UnboxingType_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UnboxingType): UnboxingType {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Album]): Album | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n28(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MusicLoop]): MusicLoop | null {
    return value.length === 0 ? null : from_candid_MusicLoop_n42(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Letter]): Promise<Letter | null> {
    return value.length === 0 ? null : await from_candid_Letter_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Scrapbook]): Scrapbook | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_ScrapbookPost>]): Array<ScrapbookPost> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    besties: Array<Principal>;
    avatar: [] | [_ExternalBlob];
}): Promise<{
    name: string;
    besties: Array<Principal>;
    avatar?: ExternalBlob;
}> {
    return {
        name: value.name,
        besties: value.besties,
        avatar: record_opt_to_undefined(await from_candid_opt_n30(_uploadFile, _downloadFile, value.avatar))
    };
}
async function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _LetterId;
    patternKey: [] | [string];
    note: string;
    createdAt: _Timestamp;
    isRead: boolean;
    sender: Principal;
    envelopeTexture: _EnvelopeTexture;
    receiverLink: string;
    secretNote: [] | [string];
    openWhenTime: [] | [_Timestamp];
    musicLoop: [] | [_MusicLoop];
    unboxingType: _UnboxingType;
    photos: Array<_Photo>;
}): Promise<{
    id: LetterId;
    patternKey?: string;
    note: string;
    createdAt: Timestamp;
    isRead: boolean;
    sender: Principal;
    envelopeTexture: EnvelopeTexture;
    receiverLink: string;
    secretNote?: string;
    openWhenTime?: Timestamp;
    musicLoop?: MusicLoop;
    unboxingType: UnboxingType;
    photos: Array<Photo>;
}> {
    return {
        id: value.id,
        patternKey: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.patternKey)),
        note: value.note,
        createdAt: value.createdAt,
        isRead: value.isRead,
        sender: value.sender,
        envelopeTexture: from_candid_EnvelopeTexture_n38(_uploadFile, _downloadFile, value.envelopeTexture),
        receiverLink: value.receiverLink,
        secretNote: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.secretNote)),
        openWhenTime: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.openWhenTime)),
        musicLoop: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.musicLoop)),
        unboxingType: from_candid_UnboxingType_n44(_uploadFile, _downloadFile, value.unboxingType),
        photos: await from_candid_vec_n46(_uploadFile, _downloadFile, value.photos)
    };
}
async function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blob: _ExternalBlob;
}): Promise<{
    blob: ExternalBlob;
}> {
    return {
        blob: await from_candid_ExternalBlob_n31(_uploadFile, _downloadFile, value.blob)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    owner: Principal;
    charms: Array<_Charm>;
}): {
    owner: Principal;
    charms: Array<Charm>;
} {
    return {
        owner: value.owner,
        charms: from_candid_vec_n52(_uploadFile, _downloadFile, value.charms)
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    charmType: _CharmType;
    labelText: string;
    presetId: string;
    position: bigint;
    customKey: [] | [string];
}): {
    id: string;
    charmType: CharmType;
    labelText: string;
    presetId: string;
    position: bigint;
    customKey?: string;
} {
    return {
        id: value.id,
        charmType: from_candid_CharmType_n55(_uploadFile, _downloadFile, value.charmType),
        labelText: value.labelText,
        presetId: value.presetId,
        position: value.position,
        customKey: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.customKey))
    };
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gingham: null;
} | {
    frosted: null;
} | {
    holographic: null;
}): EnvelopeTexture {
    return "gingham" in value ? EnvelopeTexture.gingham : "frosted" in value ? EnvelopeTexture.frosted : "holographic" in value ? EnvelopeTexture.holographic : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lofi: null;
} | {
    kawaiiPop: null;
}): MusicLoop {
    return "lofi" in value ? MusicLoop.lofi : "kawaiiPop" in value ? MusicLoop.kawaiiPop : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    musicBox: null;
} | {
    polaroidStack: null;
} | {
    strawberryJar: null;
} | {
    cloverField: null;
} | {
    fruitSoda: null;
} | {
    secretLocket: null;
} | {
    openWhen: null;
} | {
    cdStickerPeeler: null;
}): UnboxingType {
    return "musicBox" in value ? UnboxingType.musicBox : "polaroidStack" in value ? UnboxingType.polaroidStack : "strawberryJar" in value ? UnboxingType.strawberryJar : "cloverField" in value ? UnboxingType.cloverField : "fruitSoda" in value ? UnboxingType.fruitSoda : "secretLocket" in value ? UnboxingType.secretLocket : "openWhen" in value ? UnboxingType.openWhen : "cdStickerPeeler" in value ? UnboxingType.cdStickerPeeler : value;
}
function from_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    custom: null;
} | {
    preset: null;
}): CharmType {
    return "custom" in value ? CharmType.custom : "preset" in value ? CharmType.preset : value;
}
async function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Letter>): Promise<Array<Letter>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Letter_n35(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Photo>): Promise<Array<Photo>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Photo_n47(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Charm>): Array<Charm> {
    return value.map((x)=>from_candid_Charm_n53(_uploadFile, _downloadFile, x));
}
function to_candid_CharmType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CharmType): _CharmType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Charm_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Charm): _Charm {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_CreateLetterInput_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateLetterInput): Promise<_CreateLetterInput> {
    return await to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_EnvelopeTexture_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EnvelopeTexture): _EnvelopeTexture {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_MusicLoop_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MusicLoop): _MusicLoop {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
async function to_candid_Photo_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Photo): Promise<_Photo> {
    return await to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_UnboxingType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UnboxingType): _UnboxingType {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n60(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    patternKey?: string;
    note: string;
    envelopeTexture: EnvelopeTexture;
    receiverLink: string;
    secretNote?: string;
    openWhenTime?: Timestamp;
    musicLoop?: MusicLoop;
    unboxingType: UnboxingType;
    photos: Array<Photo>;
}): Promise<{
    patternKey: [] | [string];
    note: string;
    envelopeTexture: _EnvelopeTexture;
    receiverLink: string;
    secretNote: [] | [string];
    openWhenTime: [] | [_Timestamp];
    musicLoop: [] | [_MusicLoop];
    unboxingType: _UnboxingType;
    photos: Array<_Photo>;
}> {
    return {
        patternKey: value.patternKey ? candid_some(value.patternKey) : candid_none(),
        note: value.note,
        envelopeTexture: to_candid_EnvelopeTexture_n16(_uploadFile, _downloadFile, value.envelopeTexture),
        receiverLink: value.receiverLink,
        secretNote: value.secretNote ? candid_some(value.secretNote) : candid_none(),
        openWhenTime: value.openWhenTime ? candid_some(value.openWhenTime) : candid_none(),
        musicLoop: value.musicLoop ? candid_some(to_candid_MusicLoop_n18(_uploadFile, _downloadFile, value.musicLoop)) : candid_none(),
        unboxingType: to_candid_UnboxingType_n20(_uploadFile, _downloadFile, value.unboxingType),
        photos: await to_candid_vec_n22(_uploadFile, _downloadFile, value.photos)
    };
}
async function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blob: ExternalBlob;
}): Promise<{
    blob: _ExternalBlob;
}> {
    return {
        blob: await to_candid_ExternalBlob_n25(_uploadFile, _downloadFile, value.blob)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    besties: Array<Principal>;
    avatar?: ExternalBlob;
}): Promise<{
    name: string;
    besties: Array<Principal>;
    avatar: [] | [_ExternalBlob];
}> {
    return {
        name: value.name,
        besties: value.besties,
        avatar: value.avatar ? candid_some(await to_candid_ExternalBlob_n25(_uploadFile, _downloadFile, value.avatar)) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    charmType: CharmType;
    labelText: string;
    presetId: string;
    position: bigint;
    customKey?: string;
}): {
    id: string;
    charmType: _CharmType;
    labelText: string;
    presetId: string;
    position: bigint;
    customKey: [] | [string];
} {
    return {
        id: value.id,
        charmType: to_candid_CharmType_n10(_uploadFile, _downloadFile, value.charmType),
        labelText: value.labelText,
        presetId: value.presetId,
        position: value.position,
        customKey: value.customKey ? candid_some(value.customKey) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CharmType): {
    custom: null;
} | {
    preset: null;
} {
    return value == CharmType.custom ? {
        custom: null
    } : value == CharmType.preset ? {
        preset: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EnvelopeTexture): {
    gingham: null;
} | {
    frosted: null;
} | {
    holographic: null;
} {
    return value == EnvelopeTexture.gingham ? {
        gingham: null
    } : value == EnvelopeTexture.frosted ? {
        frosted: null
    } : value == EnvelopeTexture.holographic ? {
        holographic: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MusicLoop): {
    lofi: null;
} | {
    kawaiiPop: null;
} {
    return value == MusicLoop.lofi ? {
        lofi: null
    } : value == MusicLoop.kawaiiPop ? {
        kawaiiPop: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UnboxingType): {
    musicBox: null;
} | {
    polaroidStack: null;
} | {
    strawberryJar: null;
} | {
    cloverField: null;
} | {
    fruitSoda: null;
} | {
    secretLocket: null;
} | {
    openWhen: null;
} | {
    cdStickerPeeler: null;
} {
    return value == UnboxingType.musicBox ? {
        musicBox: null
    } : value == UnboxingType.polaroidStack ? {
        polaroidStack: null
    } : value == UnboxingType.strawberryJar ? {
        strawberryJar: null
    } : value == UnboxingType.cloverField ? {
        cloverField: null
    } : value == UnboxingType.fruitSoda ? {
        fruitSoda: null
    } : value == UnboxingType.secretLocket ? {
        secretLocket: null
    } : value == UnboxingType.openWhen ? {
        openWhen: null
    } : value == UnboxingType.cdStickerPeeler ? {
        cdStickerPeeler: null
    } : value;
}
async function to_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Photo>): Promise<Array<_Photo>> {
    return await Promise.all(value.map(async (x)=>await to_candid_Photo_n23(_uploadFile, _downloadFile, x)));
}
function to_candid_vec_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Charm>): Array<_Charm> {
    return value.map((x)=>to_candid_Charm_n8(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
